public enum ErrorAlMover {
    MOVIMIENTO_PERMITIDO,
    PILA_VACIA_NO_REY,
    ORDEN_NO_DESCENDENTE,
    ORDEN_NO_ASCENDENTE,
    CIMIENTO_VACIO_NO_AS,
    PILA_CARTAS_MISMO_COLOR,
    CARTA_A_MOVER_NO_BOCA_ARRIBA,
    CIMIENTO_CARTAS_DISTINTO_PALO;
}
