public enum ErrorAlMover {
    PILA_VACIA_NO_REY,
    ORDEN_NO_DESCENDENTE,
    ORDEN_NO_ASCENDENTE,
    CIMIENTO_VACIO_NO_AS,
    PILA_CARTAS_MISMO_COLOR,
    CARTA_A_MOVER_NO_BOCA_ARRIBA,
    CIMIENTO_CARTAS_DISTINTO_PALO,
    MAZO_VACIO,
    ERROR_DE_PROGRAMA,
    PILAS_VACIA_NO_PUEDE_SACAR_DEL_MAZO,
    PILA_INCOMPLETA_NO_PUEDE_IR_A_CIMIENTO
}
